import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
	const permutator = (inputArr) => {
		let result = []

		const permute = (arr, m = []) => {
			if (arr.length === 0) {
				result.push(m)
			} else {
				for (let i = 0; i < arr.length; i++) {
					let curr = arr.slice()
					let next = curr.splice(i, 1)
					permute(curr.slice(), m.concat(next))
				}
			}
		}

		permute(inputArr)

		return result
	}
	const calculateRoundRobinPermutations = () => {
		const teams = ['A', 'B', 'C', 'D']
		const games = []
		for (let i = 0; i < teams.length - 1; i++) {
			for (let j = i + 1; j < teams.length; j++) {
				games.push([teams[i], teams[j]])
			}
		}
		const possibleScores = [
			[3, 0],
			[1, 1],
			[0, 3],
		]
		// const groups = permutator(games)
		const numberOfScores = Math.pow(possibleScores.length, games.length)
		const finalScores = []

		let count = 0
		while (count < numberOfScores) {
			const base3 = count.toString(3).padStart(games.length, '0')
			const scores = base3
				.split('')
				.map((n) => possibleScores[parseInt(n)])
			const obj = {}
			games.forEach((game, gameIdx) => {
				game.forEach((team, index) => {
					obj[team] = obj[team] || 0
					obj[team] += scores[gameIdx][index]
				})
			})
			finalScores.push(obj)
			count++
		}

		return finalScores.filter(
			({ A, B, C, D }) =>
				// (A >= 3 &&
				(A >= B && B >= C && B >= D) ||
				(A >= C && C >= B && C >= D) ||
				(A >= D && D >= B && D >= C) ||
				(A <= B && A >= C && A >= D) ||
				(A <= C && A >= B && A >= D) ||
				(A <= D && A >= B && A >= C)
		).length
	}

	return (
		<div className={styles.container}>
			{JSON.stringify(calculateRoundRobinPermutations(), null, 2)}
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.tsx</code>
				</p>

				<div className={styles.grid}>
					<a href='https://nextjs.org/docs' className={styles.card}>
						<h2>Documentation &rarr;</h2>
						<p>
							Find in-depth information about Next.js features and
							API.
						</p>
					</a>

					<a href='https://nextjs.org/learn' className={styles.card}>
						<h2>Learn &rarr;</h2>
						<p>
							Learn about Next.js in an interactive course with
							quizzes!
						</p>
					</a>

					<a
						href='https://github.com/vercel/next.js/tree/canary/examples'
						className={styles.card}
					>
						<h2>Examples &rarr;</h2>
						<p>
							Discover and deploy boilerplate example Next.js
							projects.
						</p>
					</a>

					<a
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						target='_blank'
						rel='noopener noreferrer'
						className={styles.card}
					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL
							with Vercel.
						</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	)
}
